---
title: "Flex Dashboard Playground"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(palmerpenguins)
library(tidyverse)
library(ggridges)

df <- penguins

```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
df %>%
        select(-island, -sex) %>%
        pivot_longer(-species) %>%
        group_by(name) %>%
        mutate(value=scale(value)) %>%
        ungroup() %>%
        ggplot(aes(x=value, y=name, fill = species)) +
        geom_density_ridges(alpha= 0.7) +
        theme(legend.position = "top")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
df %>%
        select(-island, -sex) %>%
        pivot_longer(-species) %>%
        group_by(name) %>%
        mutate(value=scale(value)) %>%
        ungroup() %>%
        ggplot(aes(x=value, y=name, color=species)) +
        geom_boxplot() +
        theme(legend.position = "top")
```

### Chart C

```{r}
df %>%
        count(species, island) %>%
        drop_na() %>%
        group_by(species) %>%
        mutate(n = n/sum(n)) %>%
        ungroup() %>%
        ggplot(aes(x=species, y=n, fill=island)) +
        geom_col() +
        theme(legend.position = "top") +
        scale_y_continuous(labels=scales::label_percent())
```

